apiVersion: v1
kind: ServiceAccount
metadata:
  name: podpreset-cleanup
  labels:
      ds: a
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: podpreset-cleanup
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules:
- apiGroups:
  - "settings.k8s.io"
  resources:
  - "podpresets"
  verbs:
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: podpreset-cleanup
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: podpreset-cleanup
subjects:
- kind: ServiceAccount
  name: podpreset-cleanup
