apiVersion: v1
kind: ServiceAccount
metadata:
  name: podpreset-cleanup
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: podpreset-cleanup
rules:
- apiGroups:
  - "settings.k8s.io"
  resources:
  - "podpresets"
  verbs:
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: podpreset-cleanup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: podpreset-cleanup
subjects:
- kind: ServiceAccount
  name: podpreset-cleanup
